version: '3.8'

services:
  bot:
    build: .
    container_name: felty_arbitration_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python -m bot.main
