"""Updated payment_id field in Purchase model

Revision ID: 600a50f69f2f
Revises: a916ce90673a
Create Date: 2025-01-16 19:55:12.132534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600a50f69f2f'
down_revision: Union[str, None] = 'a916ce90673a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
